name: Super Kitten
favicon: null
layout_spectrum: 0.26578
typography_spectrum: 0.24542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#920000'
    - '#3d0000'
    - '#c86e00'
    - '#5a2500'
    - '#fabc00'
  brandStrength: 0.2399497926235199
  lightness: 0.22857897100038826
  saturation: 0.3032060437835753
  rhythmicContrast: 0.6171477567404509
purpose: []
